# -*- mode: python ; coding: utf-8 -*-
import os

spec_dir = os.path.abspath(SPECPATH)
root_dir = os.path.abspath(os.path.join(spec_dir, '..', '..'))

entry_point = os.path.join(root_dir, 'sarichesko', 'app.py')

a = Analysis(
    [entry_point],
    pathex=[root_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        'sarichesko',
        'sarichesko.app',
        'sarichesko.core',
        'sarichesko.core.congestion_scorer',
        'sarichesko.core.diagnostics_engine',
        'sarichesko.core.isp_probe',
        'sarichesko.core.monitor_engine',
        'sarichesko.core.recommendation_engine',
        'sarichesko.core.traffic_control_manager',
        'sarichesko.platform',
        'sarichesko.platform.base',
        'sarichesko.platform.windows',
        'sarichesko.platform.windows.controller',
        'sarichesko.platform.windows.monitor',
        'sarichesko.platform.linux',
        'sarichesko.platform.linux.controller',
        'sarichesko.platform.linux.monitor',
        'sarichesko.simulation',
        'sarichesko.simulation.engine_base',
        'sarichesko.simulation.python_sim',
        'sarichesko.simulation.algo_runners',
        'sarichesko.simulation.algo_runners.codel_sim',
        'sarichesko.simulation.algo_runners.leaky_bucket_sim',
        'sarichesko.simulation.algo_runners.red_sim',
        'sarichesko.simulation.algo_runners.token_bucket_sim',
        'sarichesko.simulation.scenarios',
        'sarichesko.simulation.scenarios.base_scenario',
        'sarichesko.storage',
        'sarichesko.storage.db',
        'sarichesko.storage.models',
        'sarichesko.storage.repository',
        'sarichesko.ui',
        'sarichesko.ui.main_window',
        'sarichesko.ui.splash',
        'sarichesko.ui.theme',
        'sarichesko.ui.views',
        'sarichesko.ui.views.compare_algorithms',
        'sarichesko.ui.views.dashboard',
        'sarichesko.ui.views.diagnose',
        'sarichesko.ui.views.history',
        'sarichesko.ui.views.live_network',
        'sarichesko.ui.views.reports',
        'sarichesko.ui.views.settings',
        'sarichesko.ui.views.simulation_lab',
        'sarichesko.ui.views.welcome',
        'sarichesko.ui.widgets',
        'sarichesko.ui.widgets.algo_comparison_chart',
        'sarichesko.ui.widgets.congestion_gauge',
        'sarichesko.ui.widgets.isp_status_panel',
        'sarichesko.ui.widgets.latency_chart',
        'sarichesko.ui.widgets.permission_dialog',
        'sarichesko.ui.widgets.rollback_dialog',
        'sarichesko.utils',
        'sarichesko.utils.elevation',
        'sarichesko.utils.export',
        'sarichesko.utils.units',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pyqtgraph',
        'tkinter',
        'PyQt5',
        'PyQt6',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='sarichesko',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='sarichesko',
)
